### ISSUE TITLE
Multiple abstracts with different languages

### ISSUE THREAD

**Issue by Truong-An-Nguyen** [ulyngs/oxforddown#39]
Hello,

Is there any options to add second abstract in different language?

I tried to update the template.tex as below, but it still render the title as "Abstract", not "Résumé"

%%%%% ABSTRACT -- Nothing to do here except comment out if you don't want it.
\begin{otherlanguage}{french} 
\begin{abstract}
	$abstract2$
\end{abstract}
\end{otherlanguage}

Thanks

**Comment by bttomio** [comment]
[Here](https://gist.github.com/bttomio/aa7bde923171cd99c3f98c22db18a91b) is how I managed to add a second abstract (French) by editing the file `_abstract.Rmd`.

It would be awesome to have an easier way :)

**Comment by Truong-An-Nguyen** [comment]
> [Here](https://gist.github.com/bttomio/aa7bde923171cd99c3f98c22db18a91b) is how I managed to add a second abstract (French) by editing the file `_abstract.Rmd`.
> 
> It would be awesome to have an easier way :)

Thanks @bttomio, it works with a small correction in the index.Rmd. I added encoding = "UTF-8" to read the French accent

```
abstract: |
  `r paste(readLines("front-and-back-matter/_abstract.Rmd",encoding = "UTF-8"), collapse = '\n  ')`
```

**Comment by bttomio** [comment]
Thanks, @Truong-An-Nguyen!

**Comment by ulyngs** [comment]
Just added an easy way to do this in 528d9ef

In **index.Rmd** you can now just go like 

```yaml
abstract: |
  `r paste(readLines("front-and-back-matter/_abstract.Rmd"), collapse = "\n  ")`
abstract-second-heading: "Resumé"
abstract-second: |
  `r paste(readLines("front-and-back-matter/_abstract_french.Rmd", encoding = "UTF-8"), collapse = "\n  ")`
```
