### ISSUE TITLE
mintoc: triple spacing between lines on second page

### ISSUE THREAD

**Issue by jadebarclay** [ulyngs/oxforddown#49]
One chapter has a long TOC, and the minitoc goes onto the second page.
The spacing is perfect on the first page, then the minitoc continues with enormous spaces between lines.

How can I fix the minitoc spacing issue, when it's only different on the second page?
Also, how can you insert a manual page break inside a long minitoc like this?

Thanks!

**Comment by jadebarclay** [comment]
Thank you. Here goes....

![image](https://user-images.githubusercontent.com/65600156/165173154-7845008e-3f47-4380-964c-d6fc58e353e8.png)
![image](https://user-images.githubusercontent.com/65600156/165173163-0501a876-b7bd-4452-a0b5-1d60fd12a268.png)


```
output:
  #bookdown::html_document2: default
  #bookdown::word_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
bib-humanities: true
documentclass: book
#bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
---
# Results {#results}
\chaptermark{Results}
\minitoc <!-- this will include a mini table of contents-->



## Descriptive Stats {#descr}
```

**Comment by jadebarclay** [comment]
What I'm trying to do:
1. Single line spacing on the second page
2. Insert a manual page break before item 3.6 (optional, but preferred)

**Comment by ulyngs** [comment]
And can you provide me an example of the actual text I need to put in a chapter to reproduce it?

**Comment by jadebarclay** [comment]
Here's the whole 03-results.Rmd

```
---
output:
  #bookdown::html_document2: default
  #bookdown::word_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
bib-humanities: true
documentclass: book
#bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
---
# Results {#results}
\chaptermark{Results}
\minitoc <!-- this will include a mini table of contents-->



## Descriptive Stats {#descr}

#### Entire Sample

#### Patient Sample

#### Clinican Sample

#### Patient Subgroups


## sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf



## sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf




## sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf






## sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf




## sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf




## sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf

### sdfklsdfjds sdfljksdl sdlfkjsljf sdlkfjsdldkjf



```
